name: Semgrep PR Scan

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request:
    branches:
      - "master"

jobs:
  semgrep:
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    uses: Talend/github-actions/.github/workflows/semgrep.yml@semgrep
    with:
      semgrep_fail_on_issues: false
      semgrep_config: "p/secrets auto"
      semgrep_severity_levels: 1
    secrets:
      github_action_token: ${{ secrets.GITHUB_TOKEN }}
